### ISSUE TITLE
Unable to Install 0.5.6

### ISSUE THREAD

**Issue by americanhanko** [idleberg/atom-build-osa#1]
`apm install build-osa`
`Installing build-osa to /Users/erichanko/.atom/packages`
`Unable to download https://www.atom.io/api/packages/build-osa/versions/0.5.6/tarball: 404`

![screen shot 2016-11-07 at 12 14 18 pm](https://cloud.githubusercontent.com/assets/8458267/20074119/bfd2e8be-a4e3-11e6-82d1-425710fe506f.png)

**Comment by idleberg** [comment]
Thank you. The tag for v0.5.6 was deleted, but not unpublished on apm. You should now be able to install v0.5.5.

**Comment by americanhanko** [comment]
All fixed, thanks.
